# Generated by Django 6.0.1 on 2026-01-17 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dev', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('citizen', 'Citizen'), ('municipality', 'Municipality'), ('truck_operator', 'Truck Operator'), ('factory', 'Factory')], max_length=30),
        ),
    ]
